version: '3.8'

services:
  ecommerce-microservice:
    image: postgres
    container_name: ecommerce-microservice
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres